"""Prove the committed data is exactly what the committed code produces.

Without this, `data/` is just a folder of CSVs someone promised were generated by the
scripts next to them. With it, a clone can verify the claim in ten seconds.
"""

from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def digest(directory: Path) -> dict[str, str]:
    return {
        path.name: hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(directory.glob("*.csv"))
    }


def run(script: str) -> None:
    subprocess.run([sys.executable, str(ROOT / "src" / script)],
                   check=True, cwd=ROOT, capture_output=True)


def test_raw_extracts_regenerate_byte_identically():
    before = digest(ROOT / "data" / "raw")
    assert before, "no raw extracts found"
    run("generate_raw_data.py")
    assert digest(ROOT / "data" / "raw") == before, (
        "regenerating the raw extracts changed them - the generator is not deterministic, "
        "or data/raw is out of date with src/generate_raw_data.py"
    )


def test_marts_rebuild_byte_identically():
    before = digest(ROOT / "data" / "marts")
    assert before, "no marts found"
    run("build_marts.py")
    assert digest(ROOT / "data" / "marts") == before, (
        "rebuilding the marts changed them - data/marts is out of date with src/sql"
    )
